FROM python:3.8-slim
LABEL maintainer="u6k.apps@gmail.com"

WORKDIR /var/myapp
COPY . /var/myapp

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get clean && \
    pip install pipenv && \
    pipenv install --ignore-pipfile --deploy

CMD ["pipenv", "-h"]
